services:
  chattiest-user:
    environment:
      - NODE_ENV=test
    build:
      context: .
      dockerfile: dockerfile.test
    container_name: chattiest-user
    volumes:
      - ./.git:/usr/src/app/.git
      - .:/usr/src/app
    ports:
      - "3000:3000"
