services:
  chattiest-user:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - .:/usr/src/app
      - ./.git:/usr/src/app/.git
    container_name: chattiest-user
    ports:
      - "3000:3000"
